mix phx.gen.html Datasets Property properties \
    bbl:integer \
    bin:integer \
    borough:integer \
    census_tract:integer \
    community_board:integer \
    comparable_rental_1_address:string \
    comparable_rental_1_boro_block_lot:string \
    comparable_rental_1_building_classification:string \
    comparable_rental_1_dist_from_coop_in_miles:float \
    comparable_rental_1_est_gross_income:integer \
    comparable_rental_1_full_market_value:integer \
    comparable_rental_1_gross_income_per_sqft:float \
    comparable_rental_1_gross_sqft:integer \
    comparable_rental_1_market_value_per_sqft:float \
    comparable_rental_1_neighborhood:string \
    comparable_rental_1_total_units:integer \
    comparable_rental_1_year_built:integer \
    comparable_rental_2_address:string \
    comparable_rental_2_boro_block_lot:string \
    comparable_rental_2_building_classification:string \
    comparable_rental_2_dist_from_coop_in_miles:float \
    comparable_rental_2_est_gross_income:integer \
    comparable_rental_2_full_market_value:integer \
    comparable_rental_2_gross_income_per_sqft:float \
    comparable_rental_2_gross_sqft:integer \
    comparable_rental_2_market_value_per_sqft:float \
    comparable_rental_2_neighborhood:string \
    comparable_rental_2_total_units:integer \
    comparable_rental_2_year_built:integer \
    council_district:integer \
    latitude:float \
    longitude:float \
    manhattan_condominium_property_address:string \
    manhattan_condominium_property_boro_block_lot:string \
    manhattan_condominium_property_building_classification:string \
    manhattan_condominium_property_condo_section:string \
    manhattan_condominium_property_est_gross_income:integer \
    manhattan_condominium_property_full_market_value:integer \
    manhattan_condominium_property_gross_income_per_sqft:float \
    manhattan_condominium_property_gross_sqft:integer \
    manhattan_condominium_property_market_value_per_sqft:float \
    manhattan_condominium_property_neighborhood:string \
    manhattan_condominium_property_total_units:integer \
    manhattan_condominium_property_year_built:integer \
    nta:string \
    postcode:integer
